(err, res) => err ? reject(err) : resolve(res)